version: "3.8"

services:
  db:
    image: postgres:15.6
    restart: always
    user: "999:999"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh /app/entrypoint.sh
    user: "1000:1000"
    volumes:
      - ./stolichny:/app
      - staticfiles:/vol/web/static
      - media_volume:/vol/web/media:rw
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
    expose:
      - "8000"
    #read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - internal
      - frontend
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 512M

  nginx:
    image: nginx:1.25.3
    restart: always
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-main.conf:/etc/nginx/nginx.conf:ro   # üëâ –≥–ª–æ–±–∞–ª—å–Ω—ã–π –∫–æ–Ω—Ñ–∏–≥
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # üëâ —Å–µ—Ä–≤–µ—Ä–Ω—ã–π –±–ª–æ–∫
      - media_volume:/vol/web/media:ro
      - staticfiles:/vol/web/static
      - ./nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/stolichny/nginx/ssl:/etc/nginx/ssl:ro
    #read_only: true
    privileged: false
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
    networks:
      - frontend
    deploy:
      resources:
        limits:
          cpus: "0.30"

volumes:
  postgres_data:
  media_volume:
  staticfiles:
    driver: local

networks:
  internal:
    internal: true
  frontend:

